package common

type ErrorCode int

const (
	ERROR_OK = -1 //正确码
	_        = iota + 100000
	// 通用
	ERROR_UNKNOW
	ERROR_REQUEST_UNKNOW
	ERROR_REQUEST_INTERNAL_ERROR_502
	ERROR_REQUEST_INTERNAL_ERROR_500
	ERROR_REQUEST_INTERNAL_ERROR_404
	ERROR_REQUEST_INTERNAL_ERROR_400
	ERROR_REQUEST_PARAMS
	ERROR_UNMARSHAL
	ERROR_MARSHAL
	ERROR_RET_IS_ERROR
	ERROR_RET_STRUCT_WRONG
	ERROR_REDIS_KEY_NOT_EXISTS
	ERROR_REDIS_CALL_ERROR
	ERROR_REQUEST_WARNING_DURATION
)
